apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  name: param-taskrun
spec:
  taskRef:
    name: param-task
  inputs:
    params:
      - name: command
        value: "uname"
      - name: flags
        value: 
          - "-r"
          - "-m"