apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: secret-task
spec:
  inputs:
    params:
    - name: secret
      type: string
      description: name of the secret
      default: registry-auth
  steps:
  - name: show
    image: ubuntu
    command: ["bash"]
    args: ["-c", "ls -la /var/secretfiles && echo \"secret env variable USERNAME: $USERNAME \""]
    env:
    - name: USERNAME
      valueFrom:
        secretKeyRef:
          name: $(inputs.params.secret)
          key: username
    volumeMounts:
    - name: secretmount
      mountPath: /var/secretfiles
  volumes:
  - name: secretmount
    secret:
      secretName: "$(inputs.params.secret)"
