apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  name: helloworld-java-spring-maven-build-taskrun
spec:
  taskRef:
    name: maven-build-task
  inputs:
    resources:
      - name: source
        resourceRef:
          name: helloworld-java-spring-github
    params:
      - name: mavenTag
        value: "3.6.2-jdk-8"
      - name: ARGS
        value:
          - clean
          - package
      - name: pathToPom
        value: /workspace/source/helloworld-java-spring
  outputs:
    resources:
      - name: target
        resourceRef:
          name: gcs-storage