apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  name: helloworld-java-spring-docker-build-taskrun
spec:
  taskRef:
    name: git-docker-build-task
  inputs:
    resources:
      - name: source
        resourceRef:
          name: helloworld-java-spring-github
    params:
      - name: pathToDockerFile
        value: Dockerfile
      - name: pathToContext
        value: /workspace/source/helloworld-java-spring
  outputs:
    resources:
      - name: builtImage
        resourceRef:
          name: helloworld-java-spring-image