apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: java-spring-pipeline
spec:
  resources:
    - name: source-repo
      type: git
    - name: web-image
      type: image
  tasks:
    - name: build-java-spring
      taskRef:
        name: git-docker-build-task
      params:
        - name: pathToDockerFile
          value: Dockerfile
        - name: pathToContext
          value: /workspace/source/helloworld-java-spring
      resources:
        inputs:
          - name: source
            resource: source-repo
        outputs:
          - name: builtImage
            resource: web-image
    - name: deploy-java-spring
      taskRef:
        name: deploy-kubectl
      resources:
        inputs:
          - name: source
            resource: source-repo
          - name: image
            resource: web-image
            from:
              - build-java-spring
      params:
        - name: path
          value: /workspace/source/helloworld-java-spring/deployment.yaml
        - name: yamlPathToImage
          value: "spec.template.spec.containers[0].image"
